-- MySQL Script generated by MySQL Workbench
-- Wed Dec  3 16:47:09 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tfi_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tfi_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tfi_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `tfi_bd` ;

-- -----------------------------------------------------
-- Table `tfi_bd`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`carrito_de_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`carrito_de_compra` (
  `id_Carrito` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `canal` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Carrito`),
  INDEX `fk_carrito_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tfi_bd`.`cliente` (`id_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`categoria` (
  `id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Categoria`),
  UNIQUE INDEX `uq_categoria_nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`producto` (
  `id_Producto` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `SKU` VARCHAR(50) NOT NULL,
  `Precio_Lista` DECIMAL(10,2) NOT NULL,
  `Estado` VARCHAR(50) NOT NULL,
  `fechaAlta` DATETIME NOT NULL,
  PRIMARY KEY (`id_Producto`),
  UNIQUE INDEX `uq_producto_sku` (`SKU` ASC) VISIBLE,
  UNIQUE INDEX `uq_producto_nombre` (`Nombre` ASC) VISIBLE,
  INDEX `fk_producto_categoria` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `tfi_bd`.`categoria` (`id_Categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`carrito_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`carrito_producto` (
  `carrito_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`carrito_id`, `producto_id`),
  UNIQUE INDEX `uq_carrito_producto` (`carrito_id` ASC, `producto_id` ASC) VISIBLE,
  INDEX `fk_carritop_producto` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_carritop_carrito`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `tfi_bd`.`carrito_de_compra` (`id_Carrito`),
  CONSTRAINT `fk_carritop_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`estado_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`estado_devolucion` (
  `id_EstDevol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_EstDevol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`sucursal` (
  `id_Sucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Sucursal`),
  UNIQUE INDEX `uq_sucursal_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`rol_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`rol_personal` (
  `id_Rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Rol`),
  UNIQUE INDEX `uq_rol_personal_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`personal` (
  `id_Personal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id_Personal`),
  UNIQUE INDEX `uq_personal_email` (`email` ASC) VISIBLE,
  INDEX `fk_personal_rol` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_personal_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `tfi_bd`.`rol_personal` (`id_Rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`orden_de_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`orden_de_compra` (
  `id_Orden` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `sucursalOrigen_id` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `canal` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `usuario_creacion_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Orden`),
  INDEX `fk_orden_cliente` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_orden_sucursal` (`sucursalOrigen_id` ASC) VISIBLE,
  INDEX `fk_orden_usuario_crea` (`usuario_creacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tfi_bd`.`cliente` (`id_Cliente`),
  CONSTRAINT `fk_orden_sucursal`
    FOREIGN KEY (`sucursalOrigen_id`)
    REFERENCES `tfi_bd`.`sucursal` (`id_Sucursal`),
  CONSTRAINT `fk_orden_usuario_crea`
    FOREIGN KEY (`usuario_creacion_id`)
    REFERENCES `tfi_bd`.`personal` (`id_Personal`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`devolucion` (
  `id_Devolucion` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NOT NULL,
  `estado_devolucion_id` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `motivo` TEXT NULL DEFAULT NULL,
  `personal_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Devolucion`),
  INDEX `fk_devolucion_orden` (`orden_id` ASC) VISIBLE,
  INDEX `fk_devolucion_estado` (`estado_devolucion_id` ASC) VISIBLE,
  INDEX `fk_devolucion_personal` (`personal_id` ASC) VISIBLE,
  CONSTRAINT `fk_devolucion_estado`
    FOREIGN KEY (`estado_devolucion_id`)
    REFERENCES `tfi_bd`.`estado_devolucion` (`id_EstDevol`),
  CONSTRAINT `fk_devolucion_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`),
  CONSTRAINT `fk_devolucion_personal`
    FOREIGN KEY (`personal_id`)
    REFERENCES `tfi_bd`.`personal` (`id_Personal`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`direccion` (
  `id_Direccion` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `alias` VARCHAR(100) NULL DEFAULT NULL,
  `esPrincipal` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_Direccion`),
  INDEX `fk_direccion_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tfi_bd`.`cliente` (`id_Cliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`transportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`transportista` (
  `id_transportista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_transportista`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`envio` (
  `id_envio` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NOT NULL,
  `direccion_id` INT NOT NULL,
  `transportista_id` INT NOT NULL,
  `costo` DECIMAL(10,2) NOT NULL,
  `trackingCode` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `personal_id` INT NULL DEFAULT NULL,
  `servicio_tracking` VARCHAR(100) NULL DEFAULT NULL,
  `url_tracking` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_envio`),
  INDEX `fk_envio_orden` (`orden_id` ASC) VISIBLE,
  INDEX `fk_envio_direccion` (`direccion_id` ASC) VISIBLE,
  INDEX `fk_envio_transportista` (`transportista_id` ASC) VISIBLE,
  INDEX `fk_envio_personal` (`personal_id` ASC) VISIBLE,
  CONSTRAINT `fk_envio_direccion`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `tfi_bd`.`direccion` (`id_Direccion`),
  CONSTRAINT `fk_envio_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`),
  CONSTRAINT `fk_envio_personal`
    FOREIGN KEY (`personal_id`)
    REFERENCES `tfi_bd`.`personal` (`id_Personal`),
  CONSTRAINT `fk_envio_transportista`
    FOREIGN KEY (`transportista_id`)
    REFERENCES `tfi_bd`.`transportista` (`id_transportista`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`tipo_metodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`tipo_metodo` (
  `id_Tipomet` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Tipomet`),
  UNIQUE INDEX `uq_tipo_metodo_nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`metodo_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`metodo_de_pago` (
  `id_Metodo` INT NOT NULL AUTO_INCREMENT,
  `tipo_metodo_id` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Empresa` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Metodo`),
  UNIQUE INDEX `uq_metodo_nombre` (`Nombre` ASC) VISIBLE,
  INDEX `fk_metodo_tipo` (`tipo_metodo_id` ASC) VISIBLE,
  CONSTRAINT `fk_metodo_tipo`
    FOREIGN KEY (`tipo_metodo_id`)
    REFERENCES `tfi_bd`.`tipo_metodo` (`id_Tipomet`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`moneda_cripto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`moneda_cripto` (
  `id_Moneda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `simbolo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Moneda`),
  UNIQUE INDEX `uq_moneda_cripto_nombre` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `uq_moneda_cripto_simbolo` (`simbolo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`orden_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`orden_de_pago` (
  `id_Pago` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NOT NULL,
  `metodo_id` INT NOT NULL,
  `total_pagado` DECIMAL(10,2) NOT NULL,
  `moneda` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Pago`),
  INDEX `fk_pago_orden` (`orden_id` ASC) VISIBLE,
  INDEX `fk_pago_metodo` (`metodo_id` ASC) VISIBLE,
  CONSTRAINT `fk_pago_metodo`
    FOREIGN KEY (`metodo_id`)
    REFERENCES `tfi_bd`.`metodo_de_pago` (`id_Metodo`),
  CONSTRAINT `fk_pago_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`orden_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`orden_producto` (
  `orden_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`orden_id`, `producto_id`),
  UNIQUE INDEX `uq_orden_producto` (`orden_id` ASC, `producto_id` ASC) VISIBLE,
  INDEX `fk_ordenprod_producto` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordenprod_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`),
  CONSTRAINT `fk_ordenprod_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`tipo_mov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`tipo_mov` (
  `id_TipoMov` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_TipoMov`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`stockmovimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`stockmovimiento` (
  `id_StockM` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `sucursal_id` INT NOT NULL,
  `tipo_mov` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `Cantidad` INT NOT NULL,
  `Motivo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_StockM`),
  INDEX `fk_stockmov_producto` (`producto_id` ASC) VISIBLE,
  INDEX `fk_stockmov_sucursal` (`sucursal_id` ASC) VISIBLE,
  INDEX `fk_stockmov_tipomov` (`tipo_mov` ASC) VISIBLE,
  CONSTRAINT `fk_stockmov_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`),
  CONSTRAINT `fk_stockmov_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `tfi_bd`.`sucursal` (`id_Sucursal`),
  CONSTRAINT `fk_stockmov_tipomov`
    FOREIGN KEY (`tipo_mov`)
    REFERENCES `tfi_bd`.`tipo_mov` (`id_TipoMov`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`stocksucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`stocksucursal` (
  `producto_id` INT NOT NULL,
  `sucursal_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`producto_id`, `sucursal_id`),
  UNIQUE INDEX `uq_stocksucursal_sucursal_producto` (`sucursal_id` ASC, `producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_stocksuc_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`),
  CONSTRAINT `fk_stocksuc_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `tfi_bd`.`sucursal` (`id_Sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`transaccioncripto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`transaccioncripto` (
  `pago_id` INT NOT NULL,
  `moneda_cripto_id` INT NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `wallet_cliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pago_id`),
  INDEX `fk_txcripto_moneda` (`moneda_cripto_id` ASC) VISIBLE,
  CONSTRAINT `fk_txcripto_moneda`
    FOREIGN KEY (`moneda_cripto_id`)
    REFERENCES `tfi_bd`.`moneda_cripto` (`id_Moneda`),
  CONSTRAINT `fk_txcripto_pago`
    FOREIGN KEY (`pago_id`)
    REFERENCES `tfi_bd`.`orden_de_pago` (`id_Pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `tfi_bd` ;

-- -----------------------------------------------------
-- procedure sp_actualizar_categoria
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizar_categoria`(
    IN p_id          INT,
    IN p_nombre      VARCHAR(100),
    IN p_descripcion VARCHAR(100)
)
BEGIN
    UPDATE categoria
    SET Nombre      = p_nombre,
        Descripcion = p_descripcion
    WHERE id_Categoria = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_actualizar_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizar_cliente`(
    IN p_id        INT,
    IN p_nombre    VARCHAR(100),
    IN p_apellido  VARCHAR(100),
    IN p_email     VARCHAR(100),
    IN p_telefono  VARCHAR(25)
)
BEGIN
    UPDATE cliente
    SET nombre   = p_nombre,
        apellido = p_apellido,
        email    = p_email,
        telefono = p_telefono
    WHERE id_Cliente = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_actualizar_pedido
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizar_pedido`(
    IN p_id                 INT,
    IN p_cliente_id         INT,
    IN p_sucursalOrigen_id  INT,
    IN p_fecha              DATETIME,
    IN p_total              DECIMAL(10,2),
    IN p_canal              VARCHAR(50),
    IN p_estado             VARCHAR(50),
    IN p_usuario_creacion_id INT
)
BEGIN
    UPDATE orden_de_compra
    SET cliente_id         = p_cliente_id,
        sucursalOrigen_id  = p_sucursalOrigen_id,
        fecha              = p_fecha,
        total              = p_total,
        canal              = p_canal,
        estado             = p_estado,
        usuario_creacion_id = p_usuario_creacion_id
    WHERE id_Orden = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_actualizar_personal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizar_personal`(
    IN p_id       INT,
    IN p_nombre   VARCHAR(100),
    IN p_apellido VARCHAR(100),
    IN p_email    VARCHAR(100),
    IN p_rol_id   INT
)
BEGIN
    UPDATE personal
    SET nombre   = p_nombre,
        apellido = p_apellido,
        email    = p_email,
        rol_id   = p_rol_id
    WHERE id_Personal = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_actualizar_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizar_producto`(
    IN p_id INT,
    IN p_nombre VARCHAR(255),
    IN p_categoria_id INT,
    IN p_sku VARCHAR(100),
    IN p_precio DECIMAL(10,2),
    IN p_estado VARCHAR(50)
)
BEGIN
    UPDATE producto 
    SET Nombre = p_nombre,
        categoria_id = p_categoria_id,
        SKU = p_sku,
        Precio_Lista = p_precio,
        Estado = p_estado
    WHERE id_Producto = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_actualizar_sucursal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizar_sucursal`(
    IN p_id        INT,
    IN p_nombre    VARCHAR(150),
    IN p_direccion VARCHAR(255),
    IN p_provincia VARCHAR(100),
    IN p_telefono  VARCHAR(25)
)
BEGIN
    UPDATE sucursal
    SET nombre    = p_nombre,
        direccion = p_direccion,
        provincia = p_provincia,
        telefono  = p_telefono
    WHERE id_Sucursal = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_agregar_producto_carrito
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_agregar_producto_carrito`(
   IN p_carrito_id INT,
    IN p_producto_id INT,
    IN p_cantidad INT
)
BEGIN
    INSERT INTO carrito_producto (carrito_id, producto_id, cantidad)
    VALUES (p_carrito_id, p_producto_id, p_cantidad)
    ON DUPLICATE KEY UPDATE
        cantidad = cantidad + VALUES(cantidad);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_agregar_stock_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_agregar_stock_producto`(
    IN p_producto_id INT,
    IN p_sucursal_id INT,
    IN p_cantidad    INT,
    IN p_motivo      VARCHAR(255)
)
BEGIN
    DECLARE v_tipo_mov_ingreso INT;

    -- Buscar el id_TipoMov correspondiente a "Ingreso inicial"
    SELECT id_TipoMov
    INTO v_tipo_mov_ingreso
    FROM tipo_mov
    WHERE nombre = 'Ingreso inicial'
    LIMIT 1;

    -- Si no existe el tipo de movimiento, lanzar error
    IF v_tipo_mov_ingreso IS NULL THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'No existe el tipo_mov "Ingreso inicial" en la tabla tipo_mov';
    END IF;

    -- 1) Insertar / actualizar stock por sucursal
    INSERT INTO stocksucursal (producto_id, sucursal_id, cantidad)
    VALUES (p_producto_id, p_sucursal_id, p_cantidad)
    ON DUPLICATE KEY UPDATE
        cantidad = cantidad + p_cantidad;

    -- 2) Registrar el movimiento de stock
    INSERT INTO stockmovimiento (producto_id, sucursal_id, tipo_mov, fechaHora, Cantidad, Motivo)
    VALUES (p_producto_id, p_sucursal_id, v_tipo_mov_ingreso, NOW(), p_cantidad, p_motivo);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_categoria
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_categoria`(
    IN p_nombre VARCHAR(100),
    IN p_descripcion VARCHAR(100)
)
BEGIN
    -- Insertar la nueva categoría
    INSERT INTO categoria (Nombre, Descripcion) 
    VALUES (p_nombre, p_descripcion);
    
    -- Devolver el ID de la categoría recién creada
    SELECT LAST_INSERT_ID() AS id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_cliente`(
    IN p_nombre VARCHAR(100),
    IN p_apellido VARCHAR(100),
    IN p_email VARCHAR(100),
    IN p_telefono VARCHAR(25)
)
BEGIN
    INSERT INTO cliente (nombre, apellido, email, telefono) 
    VALUES (p_nombre, p_apellido, p_email, p_telefono);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_direccion
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_direccion`(
    IN p_cliente_id  INT,
    IN p_calle       VARCHAR(255),
    IN p_numero      VARCHAR(10),
    IN p_ciudad      VARCHAR(100),
    IN p_provincia   VARCHAR(100),
    IN p_pais        VARCHAR(100),
    IN p_alias       VARCHAR(100),
    IN p_esPrincipal TINYINT
)
BEGIN
    -- Si esta dirección va a ser la principal,
    -- desmarcamos cualquier otra principal del mismo cliente
    IF p_esPrincipal = 1 THEN
        UPDATE direccion
        SET esPrincipal = 0
        WHERE cliente_id = p_cliente_id;
    END IF;

    -- Insertar la nueva dirección
    INSERT INTO direccion (
        cliente_id,
        calle,
        numero,
        ciudad,
        provincia,
        pais,
        alias,
        esPrincipal
    ) VALUES (
        p_cliente_id,
        p_calle,
        p_numero,
        p_ciudad,
        p_provincia,
        p_pais,
        p_alias,
        p_esPrincipal
    );

    -- Devolver el id de la dirección creada
    SELECT LAST_INSERT_ID() AS id_Direccion;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_orden
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_orden`(
	IN p_cliente_id INT,
    IN p_sucursalOrigen_id INT,
    IN p_fecha DATETIME,
    IN p_total DECIMAL(10,2),
    IN p_canal VARCHAR(50),
    IN p_estado VARCHAR(50),
    IN p_usuario_creacion_id INT
)
BEGIN
    INSERT INTO orden_de_compra (
		cliente_id,
        sucursalOrigen_id,
        fecha,
        total,
        canal,
        estado,
        usuario_creacion_id) 
    VALUES (
		p_cliente_id,
        p_sucursalOrigen_id,
        p_fecha,
        p_total,
        p_canal,
        p_estado,
        p_usuario_creacion_id);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_pedido
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_pedido`(
	IN p_cliente_id INT,
    IN p_sucursalOrigen_id INT,
    IN p_fecha DATETIME,
    IN p_total DECIMAL(10,2),
    IN p_canal VARCHAR(50),
    IN p_estado VARCHAR(50),
    IN p_usuario_creacion_id INT
)
BEGIN
    INSERT INTO orden_de_compra (
		cliente_id,
        sucursalOrigen_id,
        fecha,
        total,
        canal,
        estado,
        usuario_creacion_id) 
    VALUES (
		p_cliente_id,
        p_sucursalOrigen_id,
        p_fecha,
        p_total,
        p_canal,
        p_estado,
        p_usuario_creacion_id);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_personal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_personal`(
    IN p_nombre VARCHAR(100),
    IN p_apellido VARCHAR(100),
    IN p_email VARCHAR(100),
    IN p_rol_id INT
)
BEGIN
    INSERT INTO personal (nombre, apellido, email, rol_id)
    VALUES (p_nombre, p_apellido, p_email, p_rol_id);

    SELECT LAST_INSERT_ID() AS id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_producto`(
    IN p_nombre VARCHAR(255),
    IN p_categoria_id INT,
    IN p_sku VARCHAR(100),
    IN p_precio DECIMAL(10,2),
    IN p_estado VARCHAR(50)
)
BEGIN
    INSERT INTO producto (Nombre, categoria_id, SKU, Precio_Lista, Estado, fechaAlta) 
    VALUES (p_nombre, p_categoria_id, p_sku, p_precio, p_estado, NOW());
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_sucursal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_sucursal`(
    IN p_nombre VARCHAR(255),
    IN p_direccion VARCHAR(255),
    IN p_provincia VARCHAR(100),
    IN p_telefono VARCHAR(25)
)
BEGIN
    INSERT INTO sucursal (nombre, direccion, provincia, telefono) 
    VALUES (p_nombre, p_direccion, p_provincia, p_telefono);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_eliminar_categoria
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_eliminar_categoria`(
    IN p_id INT
)
BEGIN
    DELETE FROM categoria
    WHERE id_Categoria = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_eliminar_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_eliminar_cliente`(
    IN p_id INT
)
BEGIN
    -- 1) Borrar productos de carritos del cliente
    DELETE cp
    FROM carrito_producto cp
    JOIN carrito_de_compra c ON cp.carrito_id = c.id_Carrito
    WHERE c.cliente_id = p_id;

    -- 2) Borrar carritos del cliente
    DELETE FROM carrito_de_compra
    WHERE cliente_id = p_id;

    -- 3) Borrar envíos de órdenes del cliente
    DELETE e
    FROM envio e
    JOIN orden_de_compra o ON e.orden_id = o.id_Orden
    WHERE o.cliente_id = p_id;

    -- 4) Borrar devoluciones de órdenes del cliente
    DELETE d
    FROM devolucion d
    JOIN orden_de_compra o ON d.orden_id = o.id_Orden
    WHERE o.cliente_id = p_id;

    -- 5) Borrar transacciones cripto de pagos de órdenes del cliente
    DELETE tc
    FROM transaccioncripto tc
    JOIN orden_de_pago op ON tc.pago_id = op.id_Pago
    JOIN orden_de_compra o ON op.orden_id = o.id_Orden
    WHERE o.cliente_id = p_id;

    -- 6) Borrar pagos de órdenes del cliente
    DELETE op
    FROM orden_de_pago op
    JOIN orden_de_compra o ON op.orden_id = o.id_Orden
    WHERE o.cliente_id = p_id;

    -- 7) Borrar detalle de productos de órdenes del cliente
    DELETE opdet
    FROM orden_producto opdet
    JOIN orden_de_compra o ON opdet.orden_id = o.id_Orden
    WHERE o.cliente_id = p_id;

    -- 8) Borrar órdenes del cliente
    DELETE FROM orden_de_compra
    WHERE cliente_id = p_id;

    -- 9) Borrar direcciones del cliente
    DELETE FROM direccion
    WHERE cliente_id = p_id;

    -- 10) Finalmente borrar el cliente
    DELETE FROM cliente
    WHERE id_Cliente = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_eliminar_pedido
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_eliminar_pedido`(
    IN p_id INT
)
BEGIN
    -- 1) Envíos de la orden
    DELETE FROM envio
    WHERE orden_id = p_id;

    -- 2) Devoluciones de la orden
    DELETE FROM devolucion
    WHERE orden_id = p_id;

    -- 3) Transacciones cripto de pagos de la orden
    DELETE tc
    FROM transaccioncripto tc
    JOIN orden_de_pago op ON tc.pago_id = op.id_Pago
    WHERE op.orden_id = p_id;

    -- 4) Pagos de la orden
    DELETE FROM orden_de_pago
    WHERE orden_id = p_id;

    -- 5) Detalle de productos de la orden
    DELETE FROM orden_producto
    WHERE orden_id = p_id;

    -- 6) Finalmente la orden
    DELETE FROM orden_de_compra
    WHERE id_Orden = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_eliminar_personal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_eliminar_personal`(
    IN p_id INT
)
BEGIN
    -- Quitar referencias al empleado en órdenes, devoluciones y envíos
    UPDATE orden_de_compra
    SET usuario_creacion_id = NULL
    WHERE usuario_creacion_id = p_id;

    UPDATE devolucion
    SET personal_id = NULL
    WHERE personal_id = p_id;

    UPDATE envio
    SET personal_id = NULL
    WHERE personal_id = p_id;

    -- Finalmente borrar el registro de personal
    DELETE FROM personal
    WHERE id_Personal = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_eliminar_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_eliminar_producto`(
    IN p_id INT
)
BEGIN
    DELETE FROM producto 
    WHERE id_Producto = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_eliminar_sucursal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_eliminar_sucursal`(
    IN p_id INT
)
BEGIN
    -- 1) Borrar envíos de órdenes de esta sucursal
    DELETE e
    FROM envio e
    JOIN orden_de_compra o ON e.orden_id = o.id_Orden
    WHERE o.sucursalOrigen_id = p_id;

    -- 2) Borrar devoluciones de órdenes de esta sucursal
    DELETE d
    FROM devolucion d
    JOIN orden_de_compra o ON d.orden_id = o.id_Orden
    WHERE o.sucursalOrigen_id = p_id;

    -- 3) Borrar transacciones cripto de pagos de órdenes de esta sucursal
    DELETE tc
    FROM transaccioncripto tc
    JOIN orden_de_pago op ON tc.pago_id = op.id_Pago
    JOIN orden_de_compra o ON op.orden_id = o.id_Orden
    WHERE o.sucursalOrigen_id = p_id;

    -- 4) Borrar pagos de órdenes de esta sucursal
    DELETE op
    FROM orden_de_pago op
    JOIN orden_de_compra o ON op.orden_id = o.id_Orden
    WHERE o.sucursalOrigen_id = p_id;

    -- 5) Borrar detalle de productos de órdenes de esta sucursal
    DELETE opdet
    FROM orden_producto opdet
    JOIN orden_de_compra o ON opdet.orden_id = o.id_Orden
    WHERE o.sucursalOrigen_id = p_id;

    -- 6) Borrar órdenes de esta sucursal
    DELETE FROM orden_de_compra
    WHERE sucursalOrigen_id = p_id;

    -- 7) Borrar movimientos de stock y stock por sucursal
    DELETE FROM stockmovimiento WHERE sucursal_id = p_id;
    DELETE FROM stocksucursal    WHERE sucursal_id = p_id;

    -- 8) Finalmente borrar la sucursal
    DELETE FROM sucursal
    WHERE id_Sucursal = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_categorias
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_categorias`()
BEGIN
    SELECT id_Categoria as id, Nombre as nombre
    FROM categoria;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_clientes
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_clientes`()
BEGIN
    SELECT id_Cliente as id, nombre, apellido, email, telefono
    FROM cliente;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_metodos_pago
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_metodos_pago`()
BEGIN
    SELECT mp.id_Metodo as id, 
           mp.Nombre as nombre, 
           mp.Empresa as empresa, 
           tm.Nombre as tipo_metodo
    FROM metodo_de_pago mp
    JOIN tipo_metodo tm ON mp.tipo_metodo_id = tm.id_Tipomet;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_orden_detalle
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_orden_detalle`(IN p_orden_id INT)
BEGIN
    SELECT o.id_Orden AS id, 
           CONCAT(c.nombre, ' ', c.apellido) AS cliente,
           s.nombre AS sucursal, 
           o.fecha, 
           o.total, 
           o.canal,
           o.estado
    FROM orden_de_compra o
    JOIN cliente c ON o.cliente_id = c.id_Cliente
    JOIN sucursal s ON o.sucursalOrigen_id = s.id_Sucursal
    WHERE o.id_Orden = p_orden_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_orden_pago
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_orden_pago`(IN p_orden_id INT)
BEGIN
    SELECT op.id_Pago as id, 
           op.total_pagado, 
           op.moneda, 
           mp.Nombre as metodo
    FROM orden_de_pago op
    JOIN metodo_de_pago mp ON op.metodo_id = mp.id_Metodo
    WHERE op.orden_id = p_orden_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_orden_productos
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_orden_productos`(IN p_orden_id INT)
BEGIN
    SELECT p.Nombre as nombre, 
           op.cantidad, 
           op.precio_unitario
    FROM orden_producto op
    JOIN producto p ON op.producto_id = p.id_Producto
    WHERE op.orden_id = p_orden_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_ordenes_compra
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_ordenes_compra`()
BEGIN
    SELECT o.id_Orden AS id, 
           CONCAT(c.nombre, ' ', c.apellido) AS cliente,
           s.nombre AS sucursal, 
           o.fecha, 
           o.total, 
           o.canal,
           o.estado
    FROM orden_de_compra o
    JOIN cliente c ON o.cliente_id = c.id_Cliente
    JOIN sucursal s ON o.sucursalOrigen_id = s.id_Sucursal;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_pedidos
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_pedidos`()
BEGIN
    SELECT o.id_Orden AS id, 
           CONCAT(c.nombre, ' ', c.apellido) AS cliente,
           s.nombre AS sucursal, 
           o.fecha, 
           o.total, 
           o.canal,
           o.estado
    FROM orden_de_compra o
    JOIN cliente c ON o.cliente_id = c.id_Cliente
    JOIN sucursal s ON o.sucursalOrigen_id = s.id_Sucursal;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_personal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_personal`()
BEGIN
    SELECT p.id_Personal as id, 
           p.nombre, 
           p.apellido, 
           p.email, 
           r.nombre as rol
    FROM personal p
    JOIN rol_personal r ON p.rol_id = r.id_Rol;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_precio_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_precio_producto`(IN p_producto_id INT)
BEGIN
    SELECT Precio_Lista as precio 
    FROM producto 
    WHERE id_Producto = p_producto_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_productos
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_productos`()
BEGIN
    SELECT p.id_Producto as id, p.Nombre as nombre, 
           c.Nombre as categoria, p.SKU as sku, 
           p.Precio_Lista as precio, p.Estado as estado 
    FROM producto p 
    JOIN categoria c ON p.categoria_id = c.id_Categoria;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_sucursales
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_sucursales`()
BEGIN
    SELECT id_Sucursal as id, nombre, direccion, provincia, telefono 
    FROM sucursal;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_transaccion_cripto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_transaccion_cripto`(IN p_pago_id INT)
BEGIN
    SELECT mc.nombre as moneda, 
           tc.hash, 
           tc.wallet_cliente
    FROM transaccioncripto tc
    JOIN moneda_cripto mc ON tc.moneda_cripto_id = mc.id_Moneda
    WHERE tc.pago_id = p_pago_id;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
