-- MySQL Script generated by MySQL Workbench
-- Wed Dec  3 10:49:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tfi_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tfi_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tfi_bd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `tfi_bd` ;

-- -----------------------------------------------------
-- Table `tfi_bd`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`cliente` (
  `id_Cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Cliente`),
  UNIQUE INDEX `uq_cliente_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`carrito_de_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`carrito_de_compra` (
  `id_Carrito` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `canal` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Carrito`),
  INDEX `fk_carrito_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrito_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tfi_bd`.`cliente` (`id_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`categoria` (
  `id_Categoria` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Categoria`),
  UNIQUE INDEX `uq_categoria_nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`producto` (
  `id_Producto` INT NOT NULL AUTO_INCREMENT,
  `categoria_id` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  `SKU` VARCHAR(50) NOT NULL,
  `Precio_Lista` DECIMAL(10,2) NOT NULL,
  `Estado` VARCHAR(50) NOT NULL,
  `fechaAlta` DATETIME NOT NULL,
  PRIMARY KEY (`id_Producto`),
  UNIQUE INDEX `uq_producto_sku` (`SKU` ASC) VISIBLE,
  UNIQUE INDEX `uq_producto_nombre` (`Nombre` ASC) VISIBLE,
  INDEX `fk_producto_categoria` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `tfi_bd`.`categoria` (`id_Categoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`carrito_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`carrito_producto` (
  `carrito_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`carrito_id`, `producto_id`),
  UNIQUE INDEX `uq_carrito_producto` (`carrito_id` ASC, `producto_id` ASC) VISIBLE,
  INDEX `fk_carritop_producto` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_carritop_carrito`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `tfi_bd`.`carrito_de_compra` (`id_Carrito`),
  CONSTRAINT `fk_carritop_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`estado_devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`estado_devolucion` (
  `id_EstDevol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_EstDevol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`sucursal` (
  `id_Sucursal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `direccion` VARCHAR(255) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(25) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Sucursal`),
  UNIQUE INDEX `uq_sucursal_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`rol_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`rol_personal` (
  `id_Rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Rol`),
  UNIQUE INDEX `uq_rol_personal_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`personal` (
  `id_Personal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id_Personal`),
  UNIQUE INDEX `uq_personal_email` (`email` ASC) VISIBLE,
  INDEX `fk_personal_rol` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_personal_rol`
    FOREIGN KEY (`rol_id`)
    REFERENCES `tfi_bd`.`rol_personal` (`id_Rol`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`orden_de_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`orden_de_compra` (
  `id_Orden` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `sucursalOrigen_id` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `canal` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `usuario_creacion_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Orden`),
  INDEX `fk_orden_cliente` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_orden_sucursal` (`sucursalOrigen_id` ASC) VISIBLE,
  INDEX `fk_orden_usuario_crea` (`usuario_creacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_orden_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tfi_bd`.`cliente` (`id_Cliente`),
  CONSTRAINT `fk_orden_sucursal`
    FOREIGN KEY (`sucursalOrigen_id`)
    REFERENCES `tfi_bd`.`sucursal` (`id_Sucursal`),
  CONSTRAINT `fk_orden_usuario_crea`
    FOREIGN KEY (`usuario_creacion_id`)
    REFERENCES `tfi_bd`.`personal` (`id_Personal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`devolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`devolucion` (
  `id_Devolucion` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NOT NULL,
  `estado_devolucion_id` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  `motivo` TEXT NULL DEFAULT NULL,
  `personal_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_Devolucion`),
  INDEX `fk_devolucion_orden` (`orden_id` ASC) VISIBLE,
  INDEX `fk_devolucion_estado` (`estado_devolucion_id` ASC) VISIBLE,
  INDEX `fk_devolucion_personal` (`personal_id` ASC) VISIBLE,
  CONSTRAINT `fk_devolucion_estado`
    FOREIGN KEY (`estado_devolucion_id`)
    REFERENCES `tfi_bd`.`estado_devolucion` (`id_EstDevol`),
  CONSTRAINT `fk_devolucion_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`),
  CONSTRAINT `fk_devolucion_personal`
    FOREIGN KEY (`personal_id`)
    REFERENCES `tfi_bd`.`personal` (`id_Personal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`direccion` (
  `id_Direccion` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NOT NULL,
  `provincia` VARCHAR(100) NOT NULL,
  `pais` VARCHAR(100) NOT NULL,
  `alias` VARCHAR(100) NULL DEFAULT NULL,
  `esPrincipal` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_Direccion`),
  INDEX `fk_direccion_cliente` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `tfi_bd`.`cliente` (`id_Cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`transportista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`transportista` (
  `id_transportista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id_transportista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`envio` (
  `id_envio` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NOT NULL,
  `direccion_id` INT NOT NULL,
  `transportista_id` INT NOT NULL,
  `costo` DECIMAL(10,2) NOT NULL,
  `trackingCode` VARCHAR(100) NULL DEFAULT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `personal_id` INT NULL DEFAULT NULL,
  `servicio_tracking` VARCHAR(100) NULL DEFAULT NULL,
  `url_tracking` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_envio`),
  INDEX `fk_envio_orden` (`orden_id` ASC) VISIBLE,
  INDEX `fk_envio_direccion` (`direccion_id` ASC) VISIBLE,
  INDEX `fk_envio_transportista` (`transportista_id` ASC) VISIBLE,
  INDEX `fk_envio_personal` (`personal_id` ASC) VISIBLE,
  CONSTRAINT `fk_envio_direccion`
    FOREIGN KEY (`direccion_id`)
    REFERENCES `tfi_bd`.`direccion` (`id_Direccion`),
  CONSTRAINT `fk_envio_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`),
  CONSTRAINT `fk_envio_personal`
    FOREIGN KEY (`personal_id`)
    REFERENCES `tfi_bd`.`personal` (`id_Personal`),
  CONSTRAINT `fk_envio_transportista`
    FOREIGN KEY (`transportista_id`)
    REFERENCES `tfi_bd`.`transportista` (`id_transportista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`tipo_metodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`tipo_metodo` (
  `id_Tipomet` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Tipomet`),
  UNIQUE INDEX `uq_tipo_metodo_nombre` (`Nombre` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`metodo_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`metodo_de_pago` (
  `id_Metodo` INT NOT NULL AUTO_INCREMENT,
  `tipo_metodo_id` INT NOT NULL,
  `Nombre` VARCHAR(100) NOT NULL,
  `Empresa` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Metodo`),
  UNIQUE INDEX `uq_metodo_nombre` (`Nombre` ASC) VISIBLE,
  INDEX `fk_metodo_tipo` (`tipo_metodo_id` ASC) VISIBLE,
  CONSTRAINT `fk_metodo_tipo`
    FOREIGN KEY (`tipo_metodo_id`)
    REFERENCES `tfi_bd`.`tipo_metodo` (`id_Tipomet`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`moneda_cripto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`moneda_cripto` (
  `id_Moneda` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `simbolo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Moneda`),
  UNIQUE INDEX `uq_moneda_cripto_nombre` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `uq_moneda_cripto_simbolo` (`simbolo` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`orden_de_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`orden_de_pago` (
  `id_Pago` INT NOT NULL AUTO_INCREMENT,
  `orden_id` INT NOT NULL,
  `metodo_id` INT NOT NULL,
  `total_pagado` DECIMAL(10,2) NOT NULL,
  `moneda` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Pago`),
  INDEX `fk_pago_orden` (`orden_id` ASC) VISIBLE,
  INDEX `fk_pago_metodo` (`metodo_id` ASC) VISIBLE,
  CONSTRAINT `fk_pago_metodo`
    FOREIGN KEY (`metodo_id`)
    REFERENCES `tfi_bd`.`metodo_de_pago` (`id_Metodo`),
  CONSTRAINT `fk_pago_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`orden_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`orden_producto` (
  `orden_id` INT NOT NULL,
  `producto_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`orden_id`, `producto_id`),
  UNIQUE INDEX `uq_orden_producto` (`orden_id` ASC, `producto_id` ASC) VISIBLE,
  INDEX `fk_ordenprod_producto` (`producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_ordenprod_orden`
    FOREIGN KEY (`orden_id`)
    REFERENCES `tfi_bd`.`orden_de_compra` (`id_Orden`),
  CONSTRAINT `fk_ordenprod_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`tipo_mov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`tipo_mov` (
  `id_TipoMov` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_TipoMov`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`stockmovimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`stockmovimiento` (
  `id_StockM` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NOT NULL,
  `sucursal_id` INT NOT NULL,
  `tipo_mov` INT NOT NULL,
  `fechaHora` DATETIME NOT NULL,
  `Cantidad` INT NOT NULL,
  `Motivo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_StockM`),
  INDEX `fk_stockmov_producto` (`producto_id` ASC) VISIBLE,
  INDEX `fk_stockmov_sucursal` (`sucursal_id` ASC) VISIBLE,
  INDEX `fk_stockmov_tipomov` (`tipo_mov` ASC) VISIBLE,
  CONSTRAINT `fk_stockmov_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`),
  CONSTRAINT `fk_stockmov_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `tfi_bd`.`sucursal` (`id_Sucursal`),
  CONSTRAINT `fk_stockmov_tipomov`
    FOREIGN KEY (`tipo_mov`)
    REFERENCES `tfi_bd`.`tipo_mov` (`id_TipoMov`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`stocksucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`stocksucursal` (
  `producto_id` INT NOT NULL,
  `sucursal_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`producto_id`, `sucursal_id`),
  UNIQUE INDEX `uq_stocksucursal_sucursal_producto` (`sucursal_id` ASC, `producto_id` ASC) VISIBLE,
  CONSTRAINT `fk_stocksuc_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `tfi_bd`.`producto` (`id_Producto`),
  CONSTRAINT `fk_stocksuc_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `tfi_bd`.`sucursal` (`id_Sucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `tfi_bd`.`transaccioncripto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tfi_bd`.`transaccioncripto` (
  `pago_id` INT NOT NULL,
  `moneda_cripto_id` INT NOT NULL,
  `hash` VARCHAR(255) NOT NULL,
  `wallet_cliente` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pago_id`),
  INDEX `fk_txcripto_moneda` (`moneda_cripto_id` ASC) VISIBLE,
  CONSTRAINT `fk_txcripto_moneda`
    FOREIGN KEY (`moneda_cripto_id`)
    REFERENCES `tfi_bd`.`moneda_cripto` (`id_Moneda`),
  CONSTRAINT `fk_txcripto_pago`
    FOREIGN KEY (`pago_id`)
    REFERENCES `tfi_bd`.`orden_de_pago` (`id_Pago`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `tfi_bd` ;

-- -----------------------------------------------------
-- procedure sp_actualizar_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_actualizar_producto`(
    IN p_id INT,
    IN p_nombre VARCHAR(255),
    IN p_categoria_id INT,
    IN p_sku VARCHAR(100),
    IN p_precio DECIMAL(10,2),
    IN p_estado VARCHAR(50)
)
BEGIN
    UPDATE producto 
    SET Nombre = p_nombre,
        categoria_id = p_categoria_id,
        SKU = p_sku,
        Precio_Lista = p_precio,
        Estado = p_estado
    WHERE id_Producto = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_agregar_producto_carrito
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_agregar_producto_carrito`(
    IN p_carrito_id INT,
    IN p_producto_id INT,
    IN p_cantidad INT
)
BEGIN
    INSERT INTO carrito_producto (carrito_id, producto_id, cantidad)
    VALUES (p_carrito_id, p_producto_id, p_cantidad);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_categoria
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_categoria`(
    IN p_nombre VARCHAR(100),
    IN p_descripcion TEXT
)
BEGIN
    -- Insertar la nueva categoría
    INSERT INTO categoria (Nombre, Descripcion) 
    VALUES (p_nombre, p_descripcion);
    
    -- Devolver el ID de la categoría recién creada
    SELECT LAST_INSERT_ID() AS id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_cliente
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_cliente`(
    IN p_nombre VARCHAR(255),
    IN p_apellido VARCHAR(255),
    IN p_email VARCHAR(255),
    IN p_telefono VARCHAR(50)
)
BEGIN
    INSERT INTO cliente (nombre, apellido, email, telefono) 
    VALUES (p_nombre, p_apellido, p_email, p_telefono);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_empleado
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_empleado`(
    IN p_nombre VARCHAR(255),
    IN p_apellido VARCHAR(255),
    IN p_cargo VARCHAR(255),
    IN p_sucursal_id INT
)
BEGIN
    INSERT INTO empleado (nombre, apellido, cargo, sucursal_id) 
    VALUES (p_nombre, p_apellido, p_cargo, p_sucursal_id);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_pedido
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_pedido`(
    IN p_cliente_id INT,
    IN p_sucursal_id INT,
    IN p_fecha DATE,
    IN p_total DECIMAL(10,2),
    IN p_estado VARCHAR(50)
)
BEGIN
    INSERT INTO orden_de_compra (cliente_id, sucursal_id, fecha, total, estado) 
    VALUES (p_cliente_id, p_sucursal_id, p_fecha, p_total, p_estado);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_producto`(
    IN p_nombre VARCHAR(255),
    IN p_categoria_id INT,
    IN p_sku VARCHAR(100),
    IN p_precio DECIMAL(10,2),
    IN p_estado VARCHAR(50)
)
BEGIN
    INSERT INTO producto (Nombre, categoria_id, SKU, Precio_Lista, Estado, fechaAlta) 
    VALUES (p_nombre, p_categoria_id, p_sku, p_precio, p_estado, NOW());
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_crear_sucursal
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_crear_sucursal`(
    IN p_nombre VARCHAR(255),
    IN p_direccion VARCHAR(255),
    IN p_provincia VARCHAR(100),
    IN p_telefono VARCHAR(50)
)
BEGIN
    INSERT INTO sucursal (nombre, direccion, provincia, telefono) 
    VALUES (p_nombre, p_direccion, p_provincia, p_telefono);
    
    -- Devolver el ID insertado
    SELECT LAST_INSERT_ID() as id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_eliminar_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_eliminar_producto`(
    IN p_id INT
)
BEGIN
    DELETE FROM producto 
    WHERE id_Producto = p_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_categorias
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_categorias`()
BEGIN
    SELECT id_Categoria as id, Nombre as nombre
    FROM categoria;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_clientes
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_clientes`()
BEGIN
    SELECT id_Cliente as id, nombre, apellido, email, telefono
    FROM cliente;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_pedidos
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_pedidos`()
BEGIN
    SELECT o.id_Orden as id, 
           CONCAT(c.nombre, ' ', c.apellido) as cliente,
           s.nombre as sucursal, 
           o.fecha, o.total, o.estado
    FROM orden_de_compra o
    JOIN cliente c ON o.cliente_id = c.id_Cliente
    JOIN sucursal s ON o.sucursal_id = s.id_Sucursal;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_precio_producto
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_precio_producto`(IN p_producto_id INT)
BEGIN
    SELECT Precio_Lista as precio 
    FROM producto 
    WHERE id_Producto = p_producto_id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_productos
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_productos`()
BEGIN
    SELECT p.id_Producto as id, p.Nombre as nombre, 
           c.Nombre as categoria, p.SKU as sku, 
           p.Precio_Lista as precio, p.Estado as estado 
    FROM producto p 
    JOIN categoria c ON p.categoria_id = c.id_Categoria;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure sp_obtener_sucursales
-- -----------------------------------------------------

DELIMITER $$
USE `tfi_bd`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_obtener_sucursales`()
BEGIN
    SELECT id_Sucursal as id, nombre, direccion, provincia, telefono 
    FROM sucursal;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
